theme: jekyll-theme-minimal
title: Akademieschriften
show_downloads: true
description: Hier finden sich alle Informationen über den Digitalisierungsprozess der Akademischriften der BBAW. Im zugehörigen Repositorium befinden sich alle relevanten Daten. Alle Daten stehen unter der Lizenz CC BY-SA 4. Kontakt - boenig at bbaw.de
