theme: jekyll-theme-minimal
logo: https://www.bbaw.de/typo3conf/ext/bbaw/Resources/Public/Images/Berlin-Brandenburgische_Akademie_der_Wissenschaften.svg
title: Akademieschriften
show_downloads: true
description: Dokumentation der Volltext-Digitalisierung der Akademischriften der BBAW im Rahmen von OCR-D. Alle Daten stehen unter der Lizenz CC BY-SA 4. Kontakt - boenig at bbaw.de
