theme: jekyll-theme-minimal
title: Akademieschriften
show_downloads:true
description: Dokumentation der Volltext-Digitalisierung der Akademischriften der BBAW im Rahme von OCR-D. 
Alle Daten stehen unter der Lizenz CC BY-SA 4. Kontakt - boenig at bbaw.de
